DROP DATABASE cs068_079_080;
CREATE DATABASE cs068_079_080;

\c cs068_079_080

CREATE TABLE USERS (USER_ID VARCHAR (10) NOT NULL, NAME VARCHAR (15), AGE INT, EMAIL_ID VARCHAR (25),UNIQUE (USER_ID), PRIMARY KEY(USER_ID, EMAIL_ID));

CREATE TABLE SCREEN (SCREEN_ID VARCHAR (10) NOT NULL, SEATS_IN_EACH_CLASS VARCHAR (15), PRIMARY KEY(SCREEN_ID));

CREATE TABLE MOVIES (MOVIE_ID VARCHAR (10) NOT NULL, MOVIE_NAME VARCHAR (25), RELEASE_DATE DATE, GENRE VARCHAR (15), UNIQUE (MOVIE_ID), PRIMARY KEY(MOVIE_ID));

CREATE TABLE SHOW (SHOW_ID VARCHAR (10)NOT NULL, TIME INT NOT NULL, SHOW_DATE DATE, UNIQUE (SHOW_ID), SCREEN_ID VARCHAR (10), MOVIE_ID VARCHAR (10), FOREIGN KEY (SCREEN_ID) REFERENCES SCREEN(SCREEN_ID),
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID), PRIMARY KEY(SHOW_ID));

CREATE TABLE BOOKING (BOOKING_ID VARCHAR (10) NOT NULL, NO_OF_TICKETS INT NOT NULL, COST INT NOT NULL, UNIQUE (BOOKING_ID), PRIMARY KEY(BOOKING_ID), USER_ID VARCHAR (10), SHOW_ID VARCHAR (10), FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),FOREIGN KEY (SHOW_ID) REFERENCES SHOW(SHOW_ID));

CREATE TABLE TICKET (TICKET_ID VARCHAR (10) NOT NULL, PRICE INT NOT NULL, CLASS VARCHAR (10), BOOKING_ID VARCHAR (10), FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID), PRIMARY KEY(TICKET_ID));
	
CREATE TABLE LANGUAGES (LANGUAGE_ID VARCHAR (10) NOT NULL, LANGUAGE_NAME VARCHAR (10) DEFAULT 'ENGLISH' NOT NULL, MOVIE_ID VARCHAR (10), FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID), PRIMARY KEY(LANGUAGE_ID));
 
CREATE TABLE THEATRE (THEATRE_ID VARCHAR (10) NOT NULL, THEATRE_NAME VARCHAR (20) NOT NULL, NO_OF_SCREENS INT, MOVIE_ID VARCHAR (10), FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID), UNIQUE (THEATRE_ID), PRIMARY KEY(THEATRE_ID));
 
CREATE TABLE REGION (CITY VARCHAR (15), PINCODE INT NOT NULL, NO_OF_THEATRES INT, THEATRE_ID VARCHAR (10), FOREIGN KEY (THEATRE_ID) REFERENCES THEATRE(THEATRE_ID), PRIMARY KEY(PINCODE));
 
CREATE TABLE MAKE_BOOKING (PAYMENT VARCHAR (20) NOT NULL, USID VARCHAR (10), BID VARCHAR (10));

CREATE TABLE FOOD_COUNTER (FOOD_ID VARCHAR (10) NOT NULL, MOVIE_ID VARCHAR (10), BOOKING_ID VARCHAR (10), FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID), FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID), PRIMARY KEY (FOOD_ID));


--Add the following constraint after the data values have been entered into the tables.

ALTER TABLE MAKE_BOOKING ADD CONSTRAINT USID FOREIGN KEY (USID) REFERENCES USERS(USER_ID);  
ALTER TABLE MAKE_BOOKING ADD CONSTRAINT BID FOREIGN KEY (BID) REFERENCES BOOKING(BOOKING_ID);






